language: python

python:
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    packages:
      - graphviz  # sphinx inheritance diagrams

install:
  - pip install --upgrade pip setuptools wheel  # install with latest tools
  - pip install --upgrade --upgrade-strategy eager .[dev]  # get latest deps

script:
  - make lint
  - make test
  - make doc

after_success:
  - coveralls
