language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

addons:
  apt:
    packages:
      - graphviz  # sphinx inheritance diagrams

install:
  - pip install --upgrade --upgrade-strategy eager .[dev]
  # Upgrade to test with the latest version of our dependencies.

script:
  - make lint
  - make test
  - make doc

after_success:
  - coveralls
